### ISSUE TITLE
Tencent API Changed, return "AUTH_FAILED"

### ISSUE THREAD

**Issue by wuuconix** [IvanNazaruk/DifferentDimensionMe-GUI#1]
Now, the api add some block way to limit.
The api now send to http header `x-sign-value`, like this
![image](https://user-images.githubusercontent.com/80732538/205947244-aa10bba7-a51d-431d-9773-70d84bcd26ef.png)
Without the correct `x-sign-value`, the server will respond `AUTH_FAILED`.
But I don't know how to generate the correct `x-sign-value`.
Wish you could find someway to bypass this or find the correct way to generate `x-sign-value`!

**Comment by IvanNazaruk** [comment]
### **I checked, and you're right!** 
I tried to use their website (https://h5.tu.qq.com/web/ai-2d/cartoon/index), but in my country and in Germany (used VPN), it says it is being upgraded, as I know it is the third or fourth day:
![image](https://user-images.githubusercontent.com/46572469/205954900-5ad03d56-07b0-40c8-914b-9766efc974da.png)
Maybe in China the site works differently than in Europe, so I will try to download a VPN with Chinese region and try to solve the problem with it.
