### ISSUE TITLE
Зацикливается если на фото нет лица

### ISSUE THREAD

**Issue by ichinya** [IvanNazaruk/DifferentDimensionMe-GUI#5]
При попытке обработки фото без лица, зацикливается с ошибкой - no face in img

И некоторые как то обошли это и могут получать аниме с фото, на которых нет лиц

**Comment by IvanNazaruk** [comment]
Да, я знаю об этой проблеме.
Этого ограничения не было, когда она вышла, но через две недели оно появилось.
Единственное решение этой проблемы, которое я знаю, — это взять лицо с любой другой фотографии и вставить его в свою фотографию.

Можно также попробовать исследовать, как обходить это автоматически, возможно, добавлять полупрозрачное лицо на все изображение или сбоку, но я думаю, что эти манипуляции могут сильно изменить выходное изображение.
