### ISSUE TITLE
Adding to page Tools and Widgets

### ISSUE THREAD

**Issue by bandit-masked** [IvanNazaruk/DifferentDimensionMe-GUI#7]
Hey,

Just wanted to let you know that I have added DifferentDimensionMe-GUI to the *Tools and Widgets* page of the DPG wiki since it's a cool app and as an example for others to learn from.

I have noticed that the website that you are referring to no longer exists. It seems to have moved to https://differentdimensionme.net/

I haven't tried, but your application may not be working correctly as of now.

The video on the Readme doesn't really want to load properly either. Maybe it's an access rights issue.

**Comment by IvanNazaruk** [comment]
Updated the code and README, checked it works, unfortunately the image must have a face and requests must be sent from Chinese ip

About the video, strangely it loads fine for me, both through VPN (different ip) and through the incognito tab.

**Comment by bandit-masked** [comment]
After testing, I noticed that the video was not playing due to my ad blocker. It works perfectly fine now.

Thanks for fixing the rest. You can close the issue now.
